name: Deploy to Amazon ECS Fargate

on:
  push:
    branches:
      - deploy # El pipeline se activa al hacer push en la rama deploy

env:
  AWS_REGION: us-east-1
  ECS_CLUSTER: cluster-innovatech-prod     # Tu clúster de ECS
  
  # Variables del Backend (Sincronizado con image_28a6a8.png)
  ECR_REPOSITORY_BACKEND: innovatech-backend
  ECS_SERVICE_BACKEND: service-innovatech-backend
  
  # Variables del Frontend (Sincronizado con image_28a6a8.png)
  ECR_REPOSITORY_FRONTEND: innovatech-frontend
  ECS_SERVICE_FRONTEND: service-innovatech-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      # 1. Autenticarse con AWS usando los Secrets actualizados de tu AWS Academy
      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      # 2. Iniciar sesión en Amazon ECR de forma nativa
      - name: Login en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 3. Compilar y subir la imagen del Backend a tu ECR nuevo (Ruta corregida según image_28a661.png)
      - name: Construir y subir imagen Backend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          cd back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY_BACKEND }}:$IMAGE_TAG .
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY_BACKEND }}:$IMAGE_TAG

      # 4. Compilar y subir la imagen del Frontend a tu ECR nuevo
      - name: Construir y subir imagen Frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          cd front_despacho
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY_FRONTEND }}:$IMAGE_TAG .
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY_FRONTEND }}:$IMAGE_TAG

      # 5. Forzar la actualización en ECS Fargate para que tome las nuevas imágenes de ECR
      - name: Desplegar actualizaciones en Amazon ECS
        run: |
          echo "Reiniciando servicios en ECS para aplicar cambios en caliente..."
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE_BACKEND }} --force-new-deployment
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE_FRONTEND }} --force-new-deployment
